import { mkdirSync, writeFileSync, cpSync, existsSync, readFileSync } from 'fs';
import { join, basename } from 'path';
import type { SkillIndex } from './indexer';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function markdownToHtml(markdown: string): string {
  let html = escapeHtml(markdown);

  // Headers
  html = html.replace(/^### (.*$)/gim, '<h3>$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2>$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1>$1</h1>');

  // Bold and italic
  html = html.replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>');
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

  // Code blocks
  html = html.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>');
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Links
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

  // Lists
  html = html.replace(/^\s*-\s+(.*$)/gim, '<li>$1</li>');
  html = html.replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>');

  // Paragraphs
  html = html.replace(/\n\n/g, '</p><p>');
  html = '<p>' + html + '</p>';

  // Clean up multiple paragraphs inside pre
  html = html.replace(/<pre><code><p>/g, '<pre><code>');
  html = html.replace(/<\/p><\/code><\/pre>/g, '</code></pre>');

  return html;
}

function pageTemplate(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { --bg: #f8f9fa; --fg: #212529; --accent: #0056b3; --muted: #6c757d; --border: #dee2e6; }
    @media (prefers-color-scheme: dark) { :root { --bg: #121212; --fg: #e9ecef; --accent: #4dabf7; --muted: #adb5bd; --border: #343a40; } }
    * { box-sizing: border-box; }
    body { font-family: system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--fg); max-width: 900px; margin: 0 auto; padding: 2rem 1rem; line-height: 1.6; }
    header { border-bottom: 1px solid var(--border); margin-bottom: 2rem; padding-bottom: 1rem; }
    h1 { font-size: 1.75rem; margin: 0 0 0.5rem; }
    h2 { font-size: 1.25rem; margin: 1.5rem 0 0.75rem; color: var(--accent); }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    .meta { color: var(--muted); font-size: 0.875rem; }
    .tag { display: inline-block; background: var(--border); padding: 0.15rem 0.5rem; border-radius: 0.25rem; font-size: 0.75rem; margin-right: 0.35rem; }
    .skill-list { list-style: none; padding: 0; }
    .skill-list li { border: 1px solid var(--border); border-radius: 0.5rem; padding: 1rem; margin-bottom: 1rem; }
    .skill-list h3 { margin: 0 0 0.5rem; font-size: 1.1rem; }
    .skill-list p { margin: 0.25rem 0; color: var(--muted); }
    pre { background: var(--border); padding: 1rem; border-radius: 0.5rem; overflow-x: auto; }
    code { font-family: 'SF Mono', Monaco, monospace; font-size: 0.9em; }
    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.8rem; text-align: center; }
  </style>
</head>
<body>
${body}
<footer>Generated by <a href="https://github.com/sovereign-shovels/agent-skills">agent-skills</a></footer>
</body>
</html>`;
}

export function exportHtml(index: SkillIndex, outDir: string): void {
  mkdirSync(outDir, { recursive: true });

  // Index page
  const skillsHtml = index.skills.map(skill => {
    const tags = (skill.frontmatter.tags || []).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join('');
    return `<li>
      <h3><a href="${encodeURIComponent(skill.id)}.html">${escapeHtml(skill.name)}</a></h3>
      <p>${escapeHtml(skill.frontmatter.description || 'No description')}</p>
      <div class="meta">${tags} <span>scope: ${escapeHtml(skill.frontmatter.scope || 'unknown')}</span></div>
    </li>`;
  }).join('');

  const indexBody = `
<header>
  <h1>Agent Skills</h1>
  <p class="meta">${index.skills.length} skill${index.skills.length === 1 ? '' : 's'} indexed</p>
</header>
<ul class="skill-list">
${skillsHtml}
</ul>`;

  writeFileSync(join(outDir, 'index.html'), pageTemplate('Agent Skills', indexBody));

  // Individual skill pages
  for (const skill of index.skills) {
    const tags = (skill.frontmatter.tags || []).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join('');
    const contentHtml = markdownToHtml(skill.content);

    const body = `
<header>
  <p class="meta"><a href="index.html">← All skills</a></p>
  <h1>${escapeHtml(skill.name)}</h1>
  <p class="meta">${escapeHtml(skill.frontmatter.description || '')}</p>
  <div class="meta">${tags} <span>scope: ${escapeHtml(skill.frontmatter.scope || 'unknown')}</span></div>
</header>
<article>
${contentHtml}
</article>`;

    writeFileSync(join(outDir, `${skill.id}.html`), pageTemplate(skill.name, body));
  }

  // Try to copy any additional assets from skill directories
  for (const skill of index.skills) {
    try {
      const entries = require('fs').readdirSync(skill.path, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.name.toLowerCase() === 'skill.md') continue;
        const src = join(skill.path, entry.name);
        const dest = join(outDir, 'assets', skill.id);
        mkdirSync(dest, { recursive: true });
        cpSync(src, join(dest, entry.name), { recursive: true });
      }
    } catch { /* ignore asset copy errors */ }
  }
}
